/* ============================================================
   Cut data.
   Names are the term you would actually hear at a counter in that
   country, not a literal translation. Butchery differs by country —
   see NOTE on each animal — so several are close equivalents rather
   than exact matches.
   ============================================================ */

const LANGS = [
  { code: 'en', label: 'EN', name: 'English' },
  { code: 'ko', label: '한국어', name: 'Korean' },
  { code: 'ja', label: '日本語', name: 'Japanese' },
  { code: 'zh', label: '中文', name: 'Chinese' }
];

const UI = {
  searchLabel:   { en: 'Search cuts',  ko: '부위 검색',       ja: '部位を検索',   zh: '搜索部位' },
  searchPh:      { en: 'Try "ribeye", "등심", "リブロース", "肋眼"…',
                   ko: '예: 등심, ribeye, 리브로스…',
                   ja: '例: リブロース, ribeye, 등심…',
                   zh: '例如：肋眼, ribeye, 등심…' },
  noResults:     { en: 'No match',     ko: '결과 없음',       ja: '該当なし',     zh: '无结果' },
  cutsIn:        { en: 'Cuts from',    ko: '이 부위의 정육',  ja: 'この部位の肉', zh: '此部位的肉' },
  bestFor:       { en: 'Best for',     ko: '조리법',          ja: '調理法',       zh: '烹饪方法' },
  alsoCalled:    { en: 'Also called',  ko: '다른 이름',       ja: '別名',         zh: '别名' },
  tapHint:       { en: 'Hover a section for names · click for detail',
                   ko: '마우스를 올리면 이름, 누르면 상세 정보',
                   ja: 'カーソルで名称・クリックで詳細',
                   zh: '悬停查看名称 · 点击查看详情' },
  clear:         { en: 'Clear',        ko: '지우기',          ja: 'クリア',       zh: '清除' }
};

const METHODS = {
  grill:  { en: 'Grill',     ko: '구이',   ja: 'グリル',     zh: '烧烤' },
  pan:    { en: 'Pan-sear',  ko: '팬구이', ja: '焼く',       zh: '煎' },
  roast:  { en: 'Roast',     ko: '로스트', ja: 'ロースト',   zh: '烤' },
  braise: { en: 'Braise',    ko: '찜·조림', ja: '煮込み',    zh: '炖' },
  stew:   { en: 'Stew',      ko: '국·탕',  ja: 'シチュー',   zh: '煲汤' },
  stir:   { en: 'Stir-fry',  ko: '볶음',   ja: '炒める',     zh: '炒' },
  bbq:    { en: 'Low & slow', ko: '훈연',  ja: '低温長時間', zh: '慢烤' },
  raw:    { en: 'Thin-sliced', ko: '샤브·구이용 박편', ja: '薄切り', zh: '涮切片' }
};

/* ---------------- BEEF ---------------- */

const BEEF = {
  id: 'beef',
  note: {
    en: 'Korea and Japan break the carcass down differently from the US — into more, smaller primals. Korean and Japanese names below are the cut you would actually buy in that spot, not a literal translation.',
    ko: '한국과 일본은 미국식 대분할과 다르게 더 잘게 나눕니다. 아래 이름은 직역이 아니라 실제로 그 자리에서 파는 부위 이름입니다.',
    ja: '韓国と日本は米国式とは異なり、より細かく分割します。以下は直訳ではなく、その部位で実際に売られている名称です。',
    zh: '韩国和日本的分割方式比美式更细。以下名称是当地实际售卖的部位名，而非直译。'
  },
  primals: [
    {
      id: 'chuck',
      names: { en: 'Chuck', ko: '목심 · 앞다리', ja: '肩ロース・ウデ', zh: '牛肩 / 肩胛' },
      desc: {
        en: 'The shoulder. Hard-working muscle, heavily marbled and full of collagen — which is why it is the best value on the animal if you give it time.',
        ko: '어깨 부위. 많이 움직이는 근육이라 결합조직이 많고 마블링도 좋습니다. 시간을 들이면 가성비가 가장 뛰어난 부위입니다.',
        ja: '肩の部位。よく動く筋肉で結合組織が多く、サシも入ります。時間をかければ最もコスパの良い部位です。',
        zh: '肩部。活动量大的肌肉，结缔组织丰富、油花分布好。只要肯花时间炖煮，性价比最高。'
      }
    },
    {
      id: 'rib',
      names: { en: 'Rib', ko: '등심 · 갈비', ja: 'リブロース・バラ', zh: '肋部 / 肋脊' },
      desc: {
        en: 'Between the shoulder and the loin. Barely used, generously marbled — this is where ribeye and prime rib come from, and it is priced accordingly.',
        ko: '어깨와 허리 사이. 거의 쓰지 않는 근육이라 마블링이 풍부합니다. 꽃등심과 립로스가 여기서 나오고, 값도 그만큼 비쌉니다.',
        ja: '肩と腰の間。ほとんど動かさないためサシが豊富。リブロースやプライムリブが取れる高価な部位です。',
        zh: '介于肩与腰之间。几乎不活动，油花丰富，肋眼与战斧牛排皆出于此，价格也相应较高。'
      }
    },
    {
      id: 'shortloin',
      names: { en: 'Short loin', ko: '채끝 · 안심', ja: 'サーロイン・ヒレ', zh: '前腰脊 / 短腰' },
      desc: {
        en: 'The most tender real estate on the animal. Strip steak on one side of the bone, tenderloin on the other — cut across both and you get a T-bone.',
        ko: '가장 연한 부위. 뼈 한쪽은 채끝, 반대쪽은 안심이고, 둘을 한 번에 자르면 티본이 됩니다.',
        ja: '最も柔らかい部位。骨の片側がサーロイン、反対側がヒレ。両方を一度に切るとTボーンになります。',
        zh: '全牛最嫩的部位。骨头一侧是西冷，另一侧是菲力，一刀两侧同切即为丁骨。'
      }
    },
    {
      id: 'sirloin',
      names: { en: 'Sirloin', ko: '보섭살 · 우둔', ja: 'ランプ・イチボ', zh: '后腰脊 / 臀腰' },
      desc: {
        en: 'Behind the loin, ahead of the leg. Leaner and firmer than short loin but with more beef flavour — the sensible weeknight steak.',
        ko: '채끝 뒤, 다리 앞. 채끝보다 기름기는 적고 단단하지만 소고기 맛은 더 진합니다. 평일 스테이크로 가장 무난합니다.',
        ja: 'サーロインの後ろ、脚の手前。脂は少なく締まっていますが、牛の旨味は濃い。普段使いのステーキに最適。',
        zh: '腰脊之后、后腿之前。比短腰更瘦实，但牛味更浓，是日常牛排的务实之选。'
      }
    },
    {
      id: 'round',
      names: { en: 'Round', ko: '우둔 · 설도', ja: 'モモ（内モモ・外モモ）', zh: '后腿 / 牛臀' },
      desc: {
        en: 'The hind leg. Very lean, very large, very cheap. Roast it rare and slice it thin, or braise it — anything in between turns to sawdust.',
        ko: '뒷다리. 기름기가 거의 없고 덩어리가 크며 쌉니다. 레어로 구워 얇게 썰거나 푹 조리세요. 어중간하게 익히면 퍽퍽해집니다.',
        ja: '後脚。非常に赤身で大きく安い。レアに焼いて薄切りにするか、煮込むか。中途半端に火を通すとパサつきます。',
        zh: '后腿。极瘦、块大、价廉。要么烤到三分后薄切，要么慢炖；火候折中只会又柴又干。'
      }
    },
    {
      id: 'brisket',
      names: { en: 'Brisket', ko: '양지 · 차돌', ja: '肩バラ・トモバラ', zh: '牛腩 / 胸腩' },
      desc: {
        en: 'The chest. Dense connective tissue that needs hours — then becomes barbecue, pho broth, or sliced thin for the grill.',
        ko: '가슴 부위. 결합조직이 단단해 오래 익혀야 합니다. 바비큐, 국물용, 또는 차돌박이처럼 얇게 썰어 굽습니다.',
        ja: '胸の部位。結合組織が密で長時間が必要。バーベキュー、スープ、薄切りで焼くのにも。',
        zh: '胸部。结缔组织致密，需长时间烹煮，可做烟熏牛胸、汤底，或切薄片烧烤。'
      }
    },
    {
      id: 'shank',
      names: { en: 'Shank', ko: '사태', ja: 'スネ', zh: '牛腱' },
      desc: {
        en: 'The leg. The toughest cut and the most collagen-rich — useless fast, superb after three hours in liquid.',
        ko: '다리 부위. 가장 질기지만 콜라겐이 가장 많습니다. 빨리 익히면 못 먹고, 세 시간 푹 끓이면 훌륭합니다.',
        ja: '脚の部位。最も硬いがコラーゲンが最多。短時間では食べられず、三時間煮ると絶品。',
        zh: '腿部。最韧但胶质最丰富。快煮难以入口，慢炖三小时则极佳。'
      }
    },
    {
      id: 'plate',
      names: { en: 'Short plate', ko: '갈비살 · 안창살', ja: 'ゲタカルビ・ハラミ', zh: '牛腹 / 五花' },
      desc: {
        en: 'The belly below the ribs. Loose-grained, fatty and intensely beefy — the home of skirt steak and Korean galbisal.',
        ko: '갈비 아래 배 부위. 결이 굵고 기름지며 소고기 맛이 진합니다. 안창살과 갈비살이 여기서 나옵니다.',
        ja: '肋骨の下の腹部。繊維が粗く脂が多い。ハラミやゲタカルビが取れます。',
        zh: '肋下腹部。纹理粗、脂肪多、牛味浓，裙边肉与牛五花皆出于此。'
      }
    },
    {
      id: 'flank',
      names: { en: 'Flank', ko: '치마살', ja: 'カイノミ・ササバラ', zh: '腹肉 / 牛腹排' },
      desc: {
        en: 'Behind the plate, under the sirloin. Lean with a pronounced grain — marinate it, cook it hot and fast, slice across the grain or regret it.',
        ko: '갈비살 뒤, 보섭살 아래. 기름기가 적고 결이 뚜렷합니다. 양념해 센 불에 빠르게 굽고, 반드시 결 반대로 써세요.',
        ja: 'バラの後ろ、ランプの下。赤身で繊維が明確。漬け込んで強火で手早く焼き、繊維に垂直に切ること。',
        zh: '腹肉之后、后腰之下。瘦且纹理明显。腌制后大火快煎，务必逆纹切。'
      }
    }
  ],
  cuts: [
    { id:'chuck-roast', primal:'chuck', methods:['braise','stew'], price:1,
      names:{ en:'Chuck roast', ko:'목심 (찜용)', ja:'肩ロース塊', zh:'牛肩肉块' },
      desc:{ en:'The default pot roast. Three hours in liquid and the collagen turns to gelatin.',
             ko:'대표적인 찜용 덩어리. 국물에 세 시간이면 결합조직이 젤라틴으로 바뀝니다.',
             ja:'定番の煮込み用ブロック。三時間煮ればコラーゲンがゼラチンに変わります。',
             zh:'经典炖肉块。慢炖三小时，胶原化为明胶。' } },
    { id:'flat-iron', primal:'chuck', methods:['grill','pan'], price:2,
      names:{ en:'Flat iron', ko:'부채살', ja:'ミスジ', zh:'板腱 / 嫩肩里脊' },
      desc:{ en:'Second-tenderest cut on the animal once the central sinew is removed, at a fraction of loin prices.',
             ko:'가운데 힘줄만 제거하면 안심 다음으로 연합니다. 값은 등심의 일부입니다.',
             ja:'中央の筋を取れば全体で二番目に柔らかい。値段はロースよりずっと安い。',
             zh:'去除中央筋膜后是全牛第二嫩的部位，价格却远低于腰脊。' } },
    { id:'chuck-short-rib', primal:'chuck', methods:['braise','grill'], price:2,
      names:{ en:'Short ribs', ko:'갈비 · LA갈비', ja:'カルビ', zh:'牛小排' },
      desc:{ en:'Bone-in, fat-marbled, forgiving. Braise whole, or cut across the bones for Korean LA-galbi.',
             ko:'뼈째 마블링이 좋아 실패가 적습니다. 통째로 조리거나 뼈를 가로로 썰어 LA갈비로 씁니다.',
             ja:'骨付きでサシが多く失敗しにくい。塊で煮込むか、骨を横切りにしてLAカルビに。',
             zh:'带骨且油花丰富，容错度高。可整块炖煮，或横切成韩式烤排骨。' } },
    { id:'ribeye', primal:'rib', methods:['grill','pan'], price:3,
      names:{ en:'Ribeye', ko:'꽃등심 · 등심', ja:'リブロース', zh:'肋眼' },
      desc:{ en:'The marbling benchmark. Fat renders into the muscle as it cooks, which is why it forgives a slightly heavy hand.',
             ko:'마블링의 기준. 구우면 지방이 근육으로 녹아들어 조금 과하게 익혀도 괜찮습니다.',
             ja:'サシの基準。焼くと脂が筋肉に溶け込むため、多少焼きすぎても許容されます。',
             zh:'油花的标杆。烹煮时脂肪融入肌肉，因此稍微过火也不易失败。' } },
    { id:'rib-roast', primal:'rib', methods:['roast'], price:3,
      names:{ en:'Rib roast / prime rib', ko:'등심 덩어리', ja:'リブロースブロック', zh:'肋眼牛排块 / 战斧' },
      desc:{ en:'Ribeye left whole on the bone. Low oven, thermometer, long rest — the classic celebration roast.',
             ko:'등심을 뼈째 통으로 둔 것. 낮은 온도, 온도계, 충분한 휴지가 핵심입니다.',
             ja:'リブロースを骨付きのまま塊で。低温、温度計、長めの休ませが要。',
             zh:'整块带骨肋眼。低温烤、用温度计、充分静置，是经典宴客烤肉。' } },
    { id:'strip', primal:'shortloin', methods:['grill','pan'], price:3,
      names:{ en:'Strip steak / New York strip', ko:'채끝', ja:'サーロイン', zh:'西冷 / 纽约客' },
      desc:{ en:'Firmer bite than ribeye with a fat cap along one edge. Render that edge first, standing the steak on it.',
             ko:'등심보다 씹는 맛이 단단하고 한쪽에 지방층이 있습니다. 세워서 그 면부터 구우세요.',
             ja:'リブロースより歯応えがあり、片側に脂身。立てて脂の面から焼き始めます。',
             zh:'口感比肋眼扎实，一侧带脂肪盖。先立起来把脂肪那面煎出油。' } },
    { id:'tenderloin', primal:'shortloin', methods:['pan','roast'], price:3,
      names:{ en:'Tenderloin / filet mignon', ko:'안심', ja:'ヒレ', zh:'菲力 / 里脊' },
      desc:{ en:'The most tender and the least flavourful — it does almost no work. Needs butter, salt, or a sauce to earn its price.',
             ko:'가장 연하지만 맛은 가장 옅습니다. 거의 움직이지 않는 근육이라 버터나 소스가 필요합니다.',
             ja:'最も柔らかいが風味は最も淡白。ほとんど動かさない筋肉なので、バターやソースが要ります。',
             zh:'最嫩但风味最淡，因为几乎不活动。需靠黄油、盐或酱汁撑起价格。' } },
    { id:'tbone', primal:'shortloin', methods:['grill'], price:3,
      names:{ en:'T-bone / porterhouse', ko:'티본 · 포터하우스', ja:'Tボーン', zh:'丁骨 / 红屋' },
      desc:{ en:'Strip and tenderloin either side of the bone. Porterhouse is the same cut taken further back, with more tenderloin.',
             ko:'뼈 양쪽에 채끝과 안심이 붙어 있습니다. 포터하우스는 더 뒤쪽에서 잘라 안심이 많은 것입니다.',
             ja:'骨の両側にサーロインとヒレ。ポーターハウスはより後方で切り、ヒレが大きい。',
             zh:'骨两侧分别是西冷与菲力。红屋取自更后方，菲力部分更大。' } },
    { id:'top-sirloin', primal:'sirloin', methods:['grill','pan'], price:2,
      names:{ en:'Top sirloin', ko:'보섭살 · 채끝등심', ja:'ランプ', zh:'上后腰脊肉' },
      desc:{ en:'Lean, firm and genuinely beefy. The best steak-per-dollar if you do not need tenderness above all.',
             ko:'기름기가 적고 단단하며 소고기 맛이 진합니다. 연함만 아니라면 가성비 최고의 스테이크입니다.',
             ja:'赤身で締まり、牛の旨味が濃い。柔らかさ優先でなければ最高のコスパ。',
             zh:'瘦实且牛味十足。若不一味追求嫩度，是性价比最高的牛排。' } },
    { id:'tri-tip', primal:'sirloin', methods:['grill','roast'], price:2,
      names:{ en:'Tri-tip', ko:'삼각살', ja:'トライチップ', zh:'三角肉 / 嫩肩' },
      desc:{ en:'A triangular muscle with the grain running two directions — find the change and cut each half separately.',
             ko:'삼각형 근육으로 결이 두 방향입니다. 결이 바뀌는 지점을 찾아 나눠 써세요.',
             ja:'三角形の筋肉で繊維が二方向。変わる位置を見つけて分けて切ります。',
             zh:'三角形肌肉，纹理分两个方向。找到转折处，分开逆纹切。' } },
    { id:'top-round', primal:'round', methods:['roast','raw'], price:1,
      names:{ en:'Top round', ko:'우둔살', ja:'内モモ', zh:'米龙 / 内后腿' },
      desc:{ en:'Big, lean and cheap. Roast beef, jerky, or sliced paper-thin for shabu-shabu.',
             ko:'크고 기름기 없고 쌉니다. 로스트비프, 육포, 샤브샤브용 박편에 씁니다.',
             ja:'大きく赤身で安い。ローストビーフ、ジャーキー、しゃぶしゃぶの薄切りに。',
             zh:'块大、瘦、便宜。适合烤牛肉、牛肉干，或切薄片涮火锅。' } },
    { id:'eye-round', primal:'round', methods:['roast','braise'], price:1,
      names:{ en:'Eye of round', ko:'홍두깨살', ja:'シンタマ・マルシン', zh:'和尚头 / 牛霖' },
      desc:{ en:'A cylinder of almost pure lean. Unforgiving — rare and thin, or braised, nothing else.',
             ko:'거의 순살코기인 원통 모양. 레어로 얇게 썰거나 푹 조리는 것 외엔 방법이 없습니다.',
             ja:'ほぼ赤身だけの円筒。レアで薄切りか煮込みか、それ以外は失敗します。',
             zh:'近乎纯瘦的圆柱肌肉。容错极低：要么三分薄切，要么慢炖。' } },
    { id:'brisket-flat', primal:'brisket', methods:['bbq','stew'], price:1,
      names:{ en:'Brisket', ko:'양지', ja:'肩バラ', zh:'牛腩 / 牛胸肉' },
      desc:{ en:'Twelve hours of smoke, or four hours of simmering for broth. There is no shortcut with this one.',
             ko:'열두 시간 훈연하거나 네 시간 끓여 국물을 냅니다. 지름길은 없습니다.',
             ja:'十二時間の燻製か、四時間の煮出しか。近道はありません。',
             zh:'要么烟熏十二小时，要么慢煮四小时熬汤。没有捷径。' } },
    { id:'chadolbagi', primal:'brisket', methods:['raw','grill'], price:2,
      names:{ en:'Brisket point, thin-sliced', ko:'차돌박이', ja:'カイノミ・特上バラ', zh:'牛胸腹薄片' },
      desc:{ en:'The fattier end frozen and shaved almost transparent. Seconds per side on a hot plate.',
             ko:'기름진 쪽을 얼려 아주 얇게 저민 것. 뜨거운 불판에 몇 초면 익습니다.',
             ja:'脂の多い側を凍らせて極薄に削ぐ。熱した鉄板で数秒。',
             zh:'较肥的一端冷冻后削成近乎透明的薄片，热铁板上每面几秒即熟。' } },
    { id:'shank-cross', primal:'shank', methods:['stew','braise'], price:1,
      names:{ en:'Shank cross-cut / osso buco', ko:'사태', ja:'スネ肉', zh:'牛腱' },
      desc:{ en:'Marrow bone in the middle, collagen all around it. The best soup cut there is.',
             ko:'가운데 사골, 주변은 결합조직. 국물용으로는 최고입니다.',
             ja:'中央に骨髄、周囲はコラーゲン。スープ用として最高の部位。',
             zh:'中间是骨髓，周围是胶质。最好的煲汤部位。' } },
    { id:'skirt', primal:'plate', methods:['grill','stir'], price:2,
      names:{ en:'Skirt steak', ko:'안창살', ja:'ハラミ', zh:'裙边肉 / 牛横膈膜' },
      desc:{ en:'Loose grain that soaks up marinade. Blistering heat, two minutes a side, cut across the grain.',
             ko:'결이 굵어 양념이 잘 뱁니다. 아주 센 불에 한 면 2분씩, 결 반대로 써세요.',
             ja:'繊維が粗く漬けだれがよく入る。強火で片面2分、繊維に垂直に切る。',
             zh:'纹理疏松易入味。极大火每面两分钟，逆纹切。' } },
    { id:'galbisal', primal:'plate', methods:['grill'], price:3,
      names:{ en:'Boneless short rib meat', ko:'갈비살', ja:'ゲタカルビ', zh:'去骨牛小排' },
      desc:{ en:'The meat between the rib bones, cut free. The centrepiece of a Korean grill table.',
             ko:'갈비뼈 사이 살을 발라낸 것. 한국식 고깃집의 주인공입니다.',
             ja:'肋骨の間の肉を外したもの。韓国焼肉の主役です。',
             zh:'肋骨之间剔下的肉，是韩式烤肉桌上的主角。' } },
    { id:'flank-steak', primal:'flank', methods:['grill','stir'], price:2,
      names:{ en:'Flank steak', ko:'치마살', ja:'ササバラ', zh:'牛腹排' },
      desc:{ en:'Broad, flat and strongly grained. Marinate, sear hard, rest, then slice thin at a sharp angle.',
             ko:'넓고 납작하며 결이 강합니다. 양념해 센 불에 굽고 쉬게 한 뒤 비스듬히 얇게 써세요.',
             ja:'幅広く平らで繊維が強い。漬けて強火で焼き、休ませてから斜め薄切りに。',
             zh:'宽扁且纹理强烈。腌制、大火煎、静置，再斜刀薄切。' } }
  ]
};

/* ---------------- PORK ---------------- */

const PORK = {
  id: 'pork',
  note: {
    en: 'Pork is where the names diverge most. Korean samgyeopsal, Japanese tontoro and Chinese meihuarou are everyday supermarket items with no clean English equivalent — the English column is an approximation.',
    ko: '돼지고기는 이름 차이가 가장 큰 고기입니다. 삼겹살, 톤토로, 메이화러우는 영어에 딱 맞는 말이 없어 영어 이름은 근사치입니다.',
    ja: '豚肉は名称の差が最も大きい。サムギョプサル、トントロ、メイファーローに正確な英語はなく、英語欄は近似です。',
    zh: '猪肉的名称差异最大。五花肉、松阪肉、梅花肉在英语中没有确切对应，英文名仅为近似。'
  },
  primals: [
    { id:'jowl',
      names:{ en:'Jowl', ko:'항정살 · 볼살', ja:'トントロ', zh:'猪颈肉 / 松阪肉' },
      desc:{ en:'The cheek and neck collar. Densely marbled with fine fat that stays firm — prized in Korea and Japan, usually cured into guanciale in the West.',
             ko:'볼과 목덜미. 고운 지방이 촘촘히 박혀 씹는 맛이 쫄깃합니다. 한국과 일본에서 인기가 높고, 서양에서는 주로 염장합니다.',
             ja:'頬から首の部分。細かいサシが密で歯応えがあります。韓国と日本で人気、西洋では主に塩漬けに。',
             zh:'脸颊与颈圈。细密油花且口感弹脆，在韩日备受推崇，西方多用于腌制。' } },
    { id:'butt',
      names:{ en:'Shoulder / Boston butt', ko:'목살', ja:'肩ロース', zh:'梅花肉 / 猪肩肉' },
      desc:{ en:'The upper shoulder, despite the name. Fat runs through it in seams, which is why it survives twelve hours of smoke and also grills well in slices.',
             ko:'이름과 달리 어깨 윗부분입니다. 지방이 결 사이로 퍼져 있어 오래 훈연해도 좋고 얇게 썰어 구워도 좋습니다.',
             ja:'名前に反して肩の上部。脂が層状に入り、長時間の燻製にも薄切りの焼きにも向きます。',
             zh:'尽管叫"臀"，实为肩上部。脂肪呈层状分布，既耐长时间慢烤，切片烧烤也很好。' } },
    { id:'picnic',
      names:{ en:'Picnic shoulder', ko:'앞다리살', ja:'ウデ（前脚）', zh:'前腿 / 猪前肘' },
      desc:{ en:'The lower shoulder and foreleg. Tougher and cheaper than the butt, with more skin and sinew — the cut for stews, sausage and braises.',
             ko:'어깨 아랫부분과 앞다리. 목살보다 질기고 싸며 껍질과 힘줄이 많아 조림, 소시지, 찜에 씁니다.',
             ja:'肩の下部と前脚。肩ロースより硬く安価で、皮と筋が多い。煮込みやソーセージ向き。',
             zh:'肩下部与前腿。比梅花肉更韧更便宜，皮与筋较多，适合炖煮与做香肠。' } },
    { id:'loin',
      names:{ en:'Loin', ko:'등심 · 안심', ja:'ロース・ヒレ', zh:'大里脊 / 通脊' },
      desc:{ en:'The long muscle down the back, and the tenderloin tucked beneath it. Very lean — this is the pork that dries out, and the reason 145 °F matters.',
             ko:'등을 따라 이어진 긴 근육과 그 아래 안심. 기름기가 거의 없어 퍽퍽해지기 쉽고, 63도가 중요한 이유입니다.',
             ja:'背に沿う長い筋肉と、その下のヒレ。非常に赤身で乾きやすく、63℃が重要な理由です。',
             zh:'沿背部的长条肌肉，下方为里脊。极瘦，最容易烹老，这正是63度之所以关键。' } },
    { id:'belly',
      names:{ en:'Belly / side', ko:'삼겹살 · 갈매기살', ja:'バラ', zh:'五花肉' },
      desc:{ en:'Alternating bands of fat and meat. Grilled in Korea, braised in China, cured into bacon in the West — the most versatile cut on the pig.',
             ko:'지방과 살코기가 층층이 번갈아 있습니다. 한국은 구이, 중국은 조림, 서양은 베이컨. 돼지에서 가장 쓰임이 넓습니다.',
             ja:'脂と赤身が交互の層。韓国では焼き、中国では煮込み、西洋ではベーコン。最も用途が広い部位。',
             zh:'肥瘦相间的层状结构。韩式烧烤、中式红烧、西式培根皆出于此，是猪身上最百搭的部位。' } },
    { id:'ham',
      names:{ en:'Ham / leg', ko:'뒷다리살', ja:'モモ', zh:'后腿 / 猪后肘' },
      desc:{ en:'The hind leg. Lean and large — cured whole into ham and prosciutto, or sold fresh in cheap lean blocks for mincing and stir-frying.',
             ko:'뒷다리. 크고 기름기가 적어 통째로 염장해 햄을 만들거나, 저렴한 살코기 덩어리로 다짐육·볶음용으로 팝니다.',
             ja:'後脚。大きく赤身で、丸ごと塩漬けにしてハムや生ハムに。または安価な赤身ブロックとして挽き肉や炒め物に。',
             zh:'后腿。大而瘦，可整只腌制成火腿，或作为廉价瘦肉块用于绞肉与炒菜。' } }
  ],
  cuts: [
    { id:'hangjeong', primal:'jowl', methods:['grill'], price:3,
      names:{ en:'Pork jowl (hangjeongsal)', ko:'항정살', ja:'トントロ', zh:'松阪猪肉' },
      desc:{ en:'A small muscle — maybe 300 g per pig. Marbled like nothing else and slightly crisp when grilled.',
             ko:'한 마리에 300g 남짓만 나오는 특수부위. 마블링이 독특하고 구우면 쫄깃합니다.',
             ja:'一頭から約300gしか取れない希少部位。独特のサシで、焼くと軽い歯応え。',
             zh:'一头猪仅约300克的稀有部位。油花独特，烤后略带脆弹口感。' } },
    { id:'guanciale', primal:'jowl', methods:['pan'], price:2,
      names:{ en:'Guanciale', ko:'관찰레 (염장 볼살)', ja:'グアンチャーレ', zh:'腌猪颊肉' },
      desc:{ en:'Cured jowl. Renders cleaner and tastes deeper than pancetta — the correct fat for carbonara and amatriciana.',
             ko:'염장한 볼살. 판체타보다 깔끔하게 녹고 맛이 깊어 카르보나라에 맞는 재료입니다.',
             ja:'塩漬けの頬肉。パンチェッタより脂がきれいに溶け、味が深い。カルボナーラの正解。',
             zh:'腌制猪颊肉。出油比意式培根更干净、风味更深，是卡博纳拉的正统选择。' } },
    { id:'moksal', primal:'butt', methods:['grill','pan'], price:2,
      names:{ en:'Pork neck steak', ko:'목살', ja:'肩ロースステーキ', zh:'梅花肉排' },
      desc:{ en:'Cut across the butt into steaks. Enough intramuscular fat to stay juicy on a grill where loin would not.',
             ko:'목살을 두툼하게 썬 것. 등심과 달리 근내지방이 충분해 구워도 촉촉합니다.',
             ja:'肩ロースを厚めに切ったもの。ロースと違い筋肉内の脂が十分で、焼いてもジューシー。',
             zh:'梅花肉横切成排。肌内脂肪充足，烧烤时不像里脊那样容易干柴。' } },
    { id:'pulled-pork', primal:'butt', methods:['bbq','braise'], price:1,
      names:{ en:'Pulled pork / whole butt', ko:'목살 덩어리', ja:'肩ロースブロック', zh:'整块梅花肉' },
      desc:{ en:'Take it to 95 °C, not to a doneness. The collagen has to melt before the meat will shred.',
             ko:'익힘 정도가 아니라 95도까지 올리세요. 결합조직이 녹아야 살이 결대로 찢어집니다.',
             ja:'焼き加減ではなく95℃まで。コラーゲンが溶けて初めてほぐれます。',
             zh:'目标是95度，而非某个熟度。胶质必须融化，肉才能撕开成丝。' } },
    { id:'apdari', primal:'picnic', methods:['braise','stir'], price:1,
      names:{ en:'Picnic shoulder', ko:'앞다리살', ja:'ウデ肉', zh:'前腿肉' },
      desc:{ en:'The everyday cheap block. Cube it for stew, mince it for dumplings, or braise it whole with the skin on.',
             ko:'가장 저렴한 살코기 덩어리. 깍둑 썰어 조리거나 다져서 만두소로, 껍질째 통으로 조리기도 합니다.',
             ja:'最も安い定番ブロック。角切りで煮込み、挽いて餃子の餡、皮付きで丸ごと煮込みにも。',
             zh:'最实惠的常用肉块。切块炖煮、绞馅包饺子，或带皮整块红烧。' } },
    { id:'jokbal', primal:'picnic', methods:['braise','stew'], price:1,
      names:{ en:'Trotter / hock', ko:'족발 · 사골', ja:'豚足', zh:'猪蹄 / 猪手' },
      desc:{ en:'Almost entirely skin, bone and collagen. Braised for hours it turns glossy and sticky — jokbal, or a Chinese red-braise.',
             ko:'껍질과 뼈, 콜라겐이 대부분. 몇 시간 조리면 쫀득하고 윤기가 납니다. 족발이나 중국식 홍샤오로.',
             ja:'ほぼ皮と骨とコラーゲン。数時間煮込むと艶やかで粘りのある食感に。',
             zh:'几乎全是皮、骨与胶质。慢炖数小时后黏糯发亮，可做韩式猪脚或红烧猪手。' } },
    { id:'pork-chop', primal:'loin', methods:['pan','grill'], price:2,
      names:{ en:'Pork chop', ko:'등심 (돈까스용)', ja:'ロース（とんかつ用）', zh:'大里脊排' },
      desc:{ en:'Bone-in holds moisture better than boneless. Brine it, sear it, pull it at 63 °C and rest — it should be faintly pink.',
             ko:'뼈가 붙은 쪽이 수분을 더 잘 잡습니다. 염지 후 구워 63도에서 꺼내 쉬게 하면 살짝 분홍빛이 돕니다.',
             ja:'骨付きの方が水分を保ちます。塩水漬けにして焼き、63℃で取り出して休ませると薄桃色に。',
             zh:'带骨比去骨更能锁住水分。盐水浸后煎，63度出锅静置，中心应呈淡粉色。' } },
    { id:'pork-tender', primal:'loin', methods:['pan','roast'], price:2,
      names:{ en:'Tenderloin', ko:'안심', ja:'ヒレ', zh:'小里脊 / 里脊芯' },
      desc:{ en:'The leanest muscle on the pig and the fastest to overcook. Ten minutes total, then rest — no longer.',
             ko:'돼지에서 가장 기름기 없는 부위이자 가장 빨리 퍽퍽해집니다. 총 10분이면 충분합니다.',
             ja:'豚で最も赤身が強く、最も早く火が入りすぎる部位。合計10分、それ以上は不要。',
             zh:'猪身上最瘦的肌肉，也最容易烹过头。总共十分钟，静置即可。' } },
    { id:'baby-back', primal:'loin', methods:['bbq','braise'], price:2,
      names:{ en:'Baby back ribs', ko:'등갈비', ja:'スペアリブ（背）', zh:'肋排 / 小排' },
      desc:{ en:'Cut from where the loin meets the spine. Shorter, leaner and quicker than spare ribs from the belly.',
             ko:'등심이 척추와 만나는 곳에서 잘라냅니다. 삼겹 쪽 갈비보다 짧고 기름기가 적어 빨리 익습니다.',
             ja:'ロースと背骨の接点から切り出します。バラ側のスペアリブより短く赤身で火が早い。',
             zh:'取自里脊与脊骨相接处。比五花处的排骨更短、更瘦、熟得更快。' } },
    { id:'samgyeopsal', primal:'belly', methods:['grill'], price:2,
      names:{ en:'Pork belly, sliced', ko:'삼겹살', ja:'サムギョプサル・バラ焼肉用', zh:'五花肉片' },
      desc:{ en:'Thick-cut belly straight on the grill, no marinade. The fat is the seasoning.',
             ko:'두껍게 썬 삼겹을 양념 없이 그대로 굽습니다. 지방이 곧 간입니다.',
             ja:'厚切りのバラを味付けせず焼くだけ。脂そのものが味付けです。',
             zh:'厚切五花直接上烤盘，无需腌制。油脂本身就是调味。' } },
    { id:'bacon', primal:'belly', methods:['pan'], price:2,
      names:{ en:'Bacon', ko:'베이컨', ja:'ベーコン', zh:'培根' },
      desc:{ en:'Belly cured in salt and sugar, usually smoked. Start it in a cold pan so the fat renders before the meat scorches.',
             ko:'삼겹을 소금과 설탕에 절여 훈연한 것. 차가운 팬에서 시작해야 지방이 먼저 녹습니다.',
             ja:'バラを塩と砂糖で漬け、燻製にしたもの。冷たいフライパンから始めると脂が先に溶けます。',
             zh:'五花经盐糖腌制并烟熏。从冷锅开始加热，脂肪才会先融出而肉不焦。' } },
    { id:'dongpo', primal:'belly', methods:['braise'], price:2,
      names:{ en:'Braised pork belly', ko:'수육 · 동파육', ja:'角煮', zh:'红烧肉 / 东坡肉' },
      desc:{ en:'Skin-on squares simmered in soy, sugar and aromatics until the fat is translucent.',
             ko:'껍질째 네모나게 썰어 간장과 설탕에 지방이 투명해질 때까지 조립니다.',
             ja:'皮付きの角切りを醤油と砂糖で脂が透き通るまで煮ます。',
             zh:'带皮切方块，以酱油、糖与香料慢炖至脂肪透明。' } },
    { id:'galmaegi', primal:'belly', methods:['grill'], price:3,
      names:{ en:'Pork skirt (diaphragm)', ko:'갈매기살', ja:'ハラミ（豚）', zh:'猪横膈膜' },
      desc:{ en:'The diaphragm, one strip per pig. Lean but deeply flavoured, and it stays tender on a hot grill.',
             ko:'한 마리에 한 줄만 나오는 횡격막. 기름기는 적지만 맛이 진하고 구워도 부드럽습니다.',
             ja:'一頭に一本の横隔膜。赤身ながら味が濃く、強火で焼いても柔らかい。',
             zh:'每头猪仅一条的横膈膜。虽瘦但风味浓郁，大火烤仍保持嫩度。' } },
    { id:'fresh-ham', primal:'ham', methods:['roast','braise'], price:1,
      names:{ en:'Fresh ham / leg roast', ko:'뒷다리 덩어리', ja:'モモブロック', zh:'后腿肉块' },
      desc:{ en:'Uncured hind leg. Very lean, so score the skin, salt it a day ahead and roast it slowly.',
             ko:'염장하지 않은 뒷다리. 기름기가 적으니 껍질에 칼집을 내고 하루 전 소금을 뿌려 천천히 구우세요.',
             ja:'塩漬けしていない後脚。赤身なので皮に切れ目を入れ、前日から塩をして低温で焼きます。',
             zh:'未腌制的后腿。极瘦，需划开猪皮、提前一天抹盐并慢烤。' } },
    { id:'prosciutto', primal:'ham', methods:['raw'], price:3,
      names:{ en:'Prosciutto / dry-cured ham', ko:'생햄 · 하몽', ja:'生ハム', zh:'风干火腿' },
      desc:{ en:'The whole leg salted and air-dried for a year or more, then sliced thin enough to see through.',
             ko:'다리를 통째로 소금에 절여 일 년 이상 말린 뒤 비칠 만큼 얇게 썹니다.',
             ja:'脚を丸ごと塩漬けにして一年以上乾燥させ、透けるほど薄く切ります。',
             zh:'整只腿以盐腌制并风干一年以上，再切至薄可透光。' } }
  ]
};

/* ---------------- CHICKEN ---------------- */

const CHICKEN = {
  id: 'chicken',
  note: {
    en: 'Chicken is butchered similarly everywhere, but the wing is divided differently: Japan separates tebasaki (tip and flat) from tebamoto (drumette), and Korean and Chinese menus usually follow suit.',
    ko: '닭은 어디서나 비슷하게 분할하지만 날개는 다릅니다. 일본은 手羽先과 手羽元를 나누고, 한국과 중국 메뉴도 대체로 이를 따릅니다.',
    ja: '鶏はどこでもほぼ同じ分割ですが、手羽は別。日本は手羽先と手羽元を分け、韓国・中国もほぼ同様です。',
    zh: '鸡的分割各地相似，但鸡翅不同：日本区分翅尖翅中与翅根，韩国与中国的菜单也大多如此。'
  },
  primals: [
    { id:'neck',
      names:{ en:'Neck', ko:'닭목', ja:'せせり（首）', zh:'鸡颈' },
      desc:{ en:'Little meat, constantly worked, surprisingly good. Grilled on skewers in Japan, otherwise it goes into the stockpot.',
             ko:'살은 적지만 계속 움직여 맛이 좋습니다. 일본에서는 꼬치로 굽고, 보통은 육수용입니다.',
             ja:'肉は少ないがよく動く部位で旨い。日本では串焼き、それ以外は出汁用。',
             zh:'肉少但活动频繁、风味出众。日本用来串烤，其余多入汤锅。' } },
    { id:'breast',
      names:{ en:'Breast', ko:'가슴살 · 닭안심', ja:'むね・ささみ', zh:'鸡胸肉 / 鸡柳' },
      desc:{ en:'White meat with almost no fat and no connective tissue. It has one correct temperature and a narrow window either side of it.',
             ko:'지방도 결합조직도 거의 없는 흰 살. 딱 맞는 온도가 하나 있고 그 폭이 매우 좁습니다.',
             ja:'脂も結合組織もほとんどない白身。正解の温度は一つで、その幅は非常に狭い。',
             zh:'几乎无脂肪、无结缔组织的白肉。只有一个正确温度，容错区间极窄。' } },
    { id:'wing',
      names:{ en:'Wing', ko:'닭날개 · 봉', ja:'手羽先・手羽元', zh:'鸡翅 / 翅根' },
      desc:{ en:'Skin-to-meat ratio is the highest on the bird, which is why wings crisp better than anything else on it.',
             ko:'살 대비 껍질 비율이 가장 높습니다. 그래서 닭에서 가장 바삭하게 익습니다.',
             ja:'肉に対する皮の比率が最も高い。だから鶏の中で最もパリッと仕上がります。',
             zh:'皮与肉的比例全鸡最高，因此最容易烤得酥脆。' } },
    { id:'back',
      names:{ en:'Back', ko:'등뼈 · 닭등', ja:'背・ガラ', zh:'鸡背 / 鸡架' },
      desc:{ en:'Mostly bone, with the two oysters buried near the hip — the best two bites on the bird, and most people throw them out with the carcass.',
             ko:'대부분 뼈지만 엉덩이 근처에 굴 모양 살이 두 점 있습니다. 가장 맛있는 부위인데 대개 뼈째 버려집니다.',
             ja:'ほぼ骨ですが、腰の近くに「そりれす」が二つ。鶏で最も旨い部位なのに、大抵は捨てられます。',
             zh:'大多是骨头，但髋部附近藏着两块"蚝肉"——全鸡最好吃的两口，却常被连骨架丢弃。' } },
    { id:'thigh',
      names:{ en:'Thigh', ko:'넓적다리살 · 정육', ja:'もも', zh:'鸡腿肉 / 去骨腿排' },
      desc:{ en:'Dark meat, worked hard, full of fat and connective tissue. It gets better past 74 °C, not worse — the opposite of breast.',
             ko:'많이 쓰는 붉은 살로 지방과 결합조직이 많습니다. 74도를 넘겨도 더 좋아집니다. 가슴살과 정반대입니다.',
             ja:'よく動く赤身で脂と結合組織が豊富。74℃を超えても悪くならず、むしろ良くなる。むねの逆です。',
             zh:'活动量大的红肉，脂肪与结缔组织丰富。超过74度反而更好，与鸡胸恰恰相反。' } },
    { id:'drumstick',
      names:{ en:'Drumstick', ko:'북채 · 닭다리', ja:'骨付きもも（チキンレッグ）', zh:'琵琶腿 / 鸡小腿' },
      desc:{ en:'The lower leg, laced with tendons that soften with time. Cheap, forgiving, and nearly impossible to dry out.',
             ko:'힘줄이 많은 아랫다리. 오래 익히면 부드러워집니다. 싸고 실패가 없으며 퍽퍽해지지 않습니다.',
             ja:'腱の多い下脚。時間をかけると柔らかくなります。安く、失敗しにくく、パサつきません。',
             zh:'布满肌腱的小腿，久煮转嫩。便宜、容错高，几乎不可能烹干。' } }
  ],
  cuts: [
    { id:'chicken-neck', primal:'neck', methods:['grill','stew'], price:1,
      names:{ en:'Neck', ko:'닭목살', ja:'せせり', zh:'鸡颈肉' },
      desc:{ en:'Two or three bites per bird, worth picking off. Salt, skewer, high heat.',
             ko:'한 마리에 두세 점뿐이지만 발라낼 값어치가 있습니다. 소금 뿌려 꼬치에 센 불로.',
             ja:'一羽に二、三口分。塩を振って串に刺し、強火で。',
             zh:'一只鸡仅两三口，值得剔下。抹盐、串起、大火。' } },
    { id:'whole-breast', primal:'breast', methods:['pan','roast'], price:2,
      names:{ en:'Breast fillet', ko:'닭가슴살', ja:'むね肉', zh:'鸡胸肉' },
      desc:{ en:'Brine thirty minutes, cook to 74 °C, rest. Every failure with breast is a temperature failure.',
             ko:'30분 염지 후 74도까지 익히고 쉬게 하세요. 가슴살 실패는 모두 온도 문제입니다.',
             ja:'30分塩水に漬け、74℃まで火を入れて休ませる。むね肉の失敗はすべて温度の失敗です。',
             zh:'盐水浸泡三十分钟，加热至74度后静置。鸡胸的失败，全是温度的失败。' } },
    { id:'tender', primal:'breast', methods:['pan','stir'], price:2,
      names:{ en:'Tenderloin', ko:'닭안심', ja:'ささみ', zh:'鸡柳 / 鸡里脊' },
      desc:{ en:'The strip under the breast, with a tough white tendon running through it. Pull the tendon out before cooking.',
             ko:'가슴살 안쪽 작은 살로 가운데 흰 힘줄이 있습니다. 조리 전에 반드시 빼내세요.',
             ja:'むねの内側の細い部位。白い筋が通っているので、調理前に取り除きます。',
             zh:'鸡胸内侧的条状肉，中间有一条白筋，烹调前务必抽掉。' } },
    { id:'tebasaki', primal:'wing', methods:['grill','roast'], price:1,
      names:{ en:'Wing flat & tip', ko:'윙 (날개)', ja:'手羽先', zh:'翅中 / 翅尖' },
      desc:{ en:'Two thin bones, a lot of skin. Dry the skin uncovered in the fridge, then cook hot for shattering crispness.',
             ko:'얇은 뼈 두 개에 껍질이 많습니다. 냉장고에서 껍질을 말린 뒤 센 불에 구우면 바삭합니다.',
             ja:'細い骨が二本と多めの皮。冷蔵庫で皮を乾かしてから高温で焼くとパリパリに。',
             zh:'两根细骨配大量鸡皮。冷藏风干表皮后高温烹制，可得极致酥脆。' } },
    { id:'tebamoto', primal:'wing', methods:['roast','braise'], price:1,
      names:{ en:'Drumette', ko:'봉 (닭봉)', ja:'手羽元', zh:'翅根' },
      desc:{ en:'The meatiest third of the wing, shaped like a small drumstick. Better braised or roasted than fried.',
             ko:'날개에서 살이 가장 많은 부분으로 작은 북채 모양입니다. 튀기기보다 굽거나 조리는 쪽이 낫습니다.',
             ja:'手羽で最も肉が多い部分。小さなドラムスティック型で、揚げるより焼く・煮る方が向きます。',
             zh:'鸡翅上肉最多的一段，形似小鼓槌。比起油炸，更适合烤或炖。' } },
    { id:'oyster', primal:'back', methods:['roast'], price:2,
      names:{ en:'Oyster', ko:'닭 굴살', ja:'そりれす', zh:'鸡蚝肉' },
      desc:{ en:'Two coin-sized pockets of dark meat in the hollow of the hip. Cook’s privilege.',
             ko:'엉덩이 뼈 오목한 곳에 있는 동전만 한 붉은 살 두 점. 요리하는 사람의 몫입니다.',
             ja:'腰骨のくぼみにある硬貨大の赤身が二つ。料理人の役得です。',
             zh:'髋骨凹处两块硬币大小的红肉，是厨师的特权。' } },
    { id:'carcass', primal:'back', methods:['stew'], price:1,
      names:{ en:'Carcass / frame', ko:'닭뼈 · 육수용', ja:'鶏ガラ', zh:'鸡架 / 鸡骨架' },
      desc:{ en:'Roast the bones first, then simmer — never boil. A rolling boil emulsifies the fat and clouds the stock.',
             ko:'뼈를 먼저 구운 뒤 은근히 끓이세요. 팔팔 끓이면 지방이 섞여 국물이 탁해집니다.',
             ja:'骨を先に焼いてから弱火で。強く沸かすと脂が乳化して濁ります。',
             zh:'先烤骨再小火慢煨，切勿大滚。滚沸会使油脂乳化，汤色浑浊。' } },
    { id:'boneless-thigh', primal:'thigh', methods:['grill','pan','braise'], price:1,
      names:{ en:'Boneless thigh', ko:'닭정육', ja:'もも肉（骨なし）', zh:'去骨鸡腿排' },
      desc:{ en:'The cut to default to. Fattier, more forgiving and cheaper than breast, and it tastes more like chicken.',
             ko:'기본으로 삼을 부위. 가슴살보다 기름지고 실패가 적고 싸며, 닭 맛이 더 진합니다.',
             ja:'標準にすべき部位。むねより脂があり、失敗しにくく、安く、鶏らしい味がします。',
             zh:'应作为首选的部位。比鸡胸更肥、更容错、更便宜，鸡味也更足。' } },
    { id:'bone-in-thigh', primal:'thigh', methods:['roast'], price:1,
      names:{ en:'Bone-in, skin-on thigh', ko:'뼈있는 닭다리살', ja:'骨付きもも', zh:'带骨鸡腿' },
      desc:{ en:'Skin side down in a cold, dry pan, then into the oven. The fat renders and the skin turns to glass.',
             ko:'차갑고 마른 팬에 껍질을 아래로 놓고 시작해 오븐으로. 지방이 녹고 껍질이 유리처럼 됩니다.',
             ja:'冷たく乾いたフライパンに皮を下にして置き、オーブンへ。脂が溶け、皮はガラスのように。',
             zh:'皮朝下放入冷的干锅，再转入烤箱。油脂融出，鸡皮脆如薄玻璃。' } },
    { id:'drum', primal:'drumstick', methods:['roast','braise','bbq'], price:1,
      names:{ en:'Drumstick', ko:'북채', ja:'骨付きもも（下）', zh:'琵琶腿' },
      desc:{ en:'Take it to 80 °C rather than 74 °C. The extra heat melts the tendons and nothing dries out.',
             ko:'74도가 아니라 80도까지 익히세요. 힘줄이 녹고 퍽퍽해지지 않습니다.',
             ja:'74℃ではなく80℃まで。腱が溶け、パサつきません。',
             zh:'加热到80度而非74度。多出的热量能融化肌腱，且完全不会变柴。' } }
  ]
};
